### PR TITLE
Started using which crate

### LINKED ISSUE #11: Switch to using `which` crate
There's a `which` crate on crates.io: https://crates.io/crates/which

I originally looked at using it but it didn't support all the things I needed, so I wrote my own implementation in commands.rs. I submitted my changes upstream and they've been merged and made it to the latest release, so we can remove the implementation in sccache2 and just use the external crate now.

### PR DESCRIPTION
**Pull request by F3real**
Fixes #11

### CODE REVIEW

**Comment by luser** [comment]
So this is failing some tests on Windows. Did you ever get a Windows build environment working?

**Comment by F3real** [comment]
Not yet, do I have to install Visual Studio for it to work ?

**Comment by luser** [comment]
I haven't tried building with the mingw rust toolchain, I've been using the msvc one. To use that one you will need to install Visual C++, but Visual C++ 2015 Community Edition is free and works fine.

**Comment by F3real** [comment]
@luser I've finally gotten scache2 working on windows :)

But it seems bug is upstream in which library. I am calling which_in function which is same as one from sccache2 with same arguments as function from sccache2 and I am getting following errors
**Bad absolute path**
**Cannot find binary path**
**Bad relative path**

Tests are passing on Linux with same code.

**Comment by F3real** [comment]
@luser All tests are green  :) I think you can merge it now.

**Comment by luser** [comment]
Thanks for the patch!

**Pull request merged**
